name: Go

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.7.x
      uses: actions/setup-go@v5
      with:
        go-version: "1.7.x"

    - name: Checkout code to GOPATH
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}

    - name: Print Build Information
      run: |
        pwd
        go version
        go env
      env:
        GOPATH: ${{ github.workspace }}/go

    - name: Unit
      run: go test -v -race ./...
      env:
        GOPATH: ${{ github.workspace }}/go
        CGO_ENABLED: 1